### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by wlrnet** [mcxiaoke/android-volley#61]
The client the exception thrown as follows:
java.lang.OutOfMemoryError
at com.android.volley.toolbox.DiskBasedCache.streamToBytes(DiskBasedCache.java:322)
at com.android.volley.toolbox.DiskBasedCache.readString(DiskBasedCache.java:540)
at com.android.volley.toolbox.DiskBasedCache.readStringStringMap(DiskBasedCache.java:562)
at com.android.volley.toolbox.DiskBasedCache$CacheHeader.readHeader(DiskBasedCache.java:403)
at com.android.volley.toolbox.DiskBasedCache.initialize(DiskBasedCache.java:156)
at com.android.volley.CacheDispatcher.run(CacheDispatcher.java:84)

Request some JSON format of data only.
Please help to analyze what's the problem?

**Comment by w4lle** [comment]
you can check your reqeustQueue is Singleton, I has solved the problem that is OOM caused by context leak with every context init a requestQueue.

**Comment by Freedom000** [comment]
Good answer~

**Comment by mcxiaoke** [comment]
maybe you should check memory leaks.

**Comment by joebowbeer** [comment]
I think this issue still exists, and is caused by a problem reading the header. The same problem can result in a NegativeArraySizeException, which is currently being caught.

**Comment by katie1006** [comment]
Hi @joebowbeer , you mentioned the NegativeArraySizeException caused by this problem has been caught. I'm assuming the fix is not included in the current release version (1.0.0) because I'm still seeing it. Do you know if it will be included in the next release?

**Comment by joebowbeer** [comment]
Hi @katie1006 , looking again at the code I see that NegativeArraySizeException (NASE) is not being caught in `readHeader`, as it would need to be in order to prevent its occurrence in this call sequence.

`streamToBytes` can throw NASE or OutOfMemoryError (OOME) but NASE is only caught in the `get` method and not in the `readHeader` method.

There's more information about this bug in an issue I filed against the official version:

https://github.com/google/volley/issues/12

In the official version, as well, NASE is only being caught in `get` and not `readHeader` where it is more likely to occur.
