### ISSUE TITLE
volley leak

### ISSUE THREAD

**Issue by BelongsH** [mcxiaoke/android-volley#96]
Encountered in the course of a problem  version 1.0.18

such as:
new StringRequest(Request.Method.GET,url, new Response.Listener<String>() {
            @Override
            public void onResponse(String response) {

            }
        }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {

            }
        });
I take request a tag .  in fragment/activity stop ,call cancel.

but now has leak :
* GC ROOT thread com.android.volley.CacheDispatcher.<Java Local> (named 'Thread-16404')

I thinks reference to the fragment/activity will also be removed

**Comment by wv1124** [comment]
Encountered in the course of a problem version 1.0.17

09-08 03:08:29.329  24385-24402/com.qianmi.qmpos D/dalvikvm﹕ WAIT_FOR_CONCURRENT_GC blocked 0ms
09-08 03:08:29.341  24385-24402/com.qianmi.qmpos D/dalvikvm﹕ GC_EXPLICIT freed 306K, 10% free 14532K/16135K, paused 1ms+1ms, total 12ms
09-08 03:08:29.545  24385-24402/com.qianmi.qmpos I/dalvikvm﹕ hprof: dumping heap strings to "/data/data/com.qianmi.qmpos/files/suspected_leak_heapdump.hprof".
09-08 03:08:29.573  24385-24402/com.qianmi.qmpos I/dalvikvm﹕ hprof: heap dump completed (15215KB)
09-08 03:08:35.825  24385-24666/com.qianmi.qmpos D/LeakCanary﹕ In com.qmpos:1.1:1.
    * com.qmpos.activity.LoginActivity has leaked:
    * GC ROOT thread com.android.volley.CacheDispatcher.<Java Local> (named 'Thread-206')
    * references com.network.GsonRequest.mListener
    * references com.activity.LoginActivity$1.this$0 (anonymous class implements com.android.volley.Response$Listener)
    * leaks comactivity.LoginActivity instance
    * Reference Key: de381c14-b0f9-40eb-a8c6-e7da793874c5
    * Device: Genymotion generic Motorola Xoom - 4.1.1 - API 16 - 1280x800 vbox86tp
    * Android Version: 4.1.1 API: 16
    * Durations: watch=5019ms, gc=113ms, heap dump=136ms, analysis=6189ms
09-08 03:08:35.825  24385-24666/com.qmpos E/LeakCanary﹕ Leak result dropped because we already store 7 leak traces.

I think the same issue.

**Comment by mcxiaoke** [comment]
may fixed in 1.0.19

**Comment by imliujun** [comment]
Encountered in the course of a problem version 1.0.19

D/LeakCanary: In                                                       
                                                            * GC ROOT thread com.android.volley.CacheDispatcher.<Java Local> (named 'Thread-20126')
                                                            * references java.util.concurrent.PriorityBlockingQueue.queue
                                                            * references array java.lang.Object[].[0]
                                                         
Device：SM-G7106
Android Version：4.3

Problems appeared in version 1.0.19

**Comment by chaozaiai** [comment]
![image](https://cloud.githubusercontent.com/assets/8943761/13835890/29a48150-ec37-11e5-9923-35872cabd13c.png)
